version: '3.8'
services:
  fastapi-app-green:
    image: rezabojnordi/fastapi-app:v1.0
    container_name: myfastapiapp-green
    ports:
      - "8080:80"
    environment:
      - ENV_VAR_NAME=value
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
